import React, { useEffect, useState } from 'react';
import { Link, NavLink, useNavigate } from 'react-router-dom';

function Navbar() {
  const [user, setUser] = useState(null);
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();
  useEffect(() => { const sync = () => { const saved = localStorage.getItem('user'); setUser(saved ? JSON.parse(saved) : null); }; sync(); window.addEventListener('storage', sync); window.addEventListener('skillbridge-auth-change', sync); return () => { window.removeEventListener('storage', sync); window.removeEventListener('skillbridge-auth-change', sync); }; }, []);
  const logout = () => { ['token', 'user', 'userRole', 'userName', 'userId'].forEach((key) => localStorage.removeItem(key)); window.dispatchEvent(new Event('skillbridge-auth-change')); setOpen(false); navigate('/login'); };
  const navClass = ({ isActive }) => `rounded-lg px-3 py-2 text-sm font-semibold transition ${isActive ? 'bg-white/15 text-white' : 'text-indigo-100 hover:bg-white/10 hover:text-white'}`;
  const Menu = () => <><NavLink to="/" onClick={() => setOpen(false)} className={navClass}>Home</NavLink><NavLink to="/skills" onClick={() => setOpen(false)} className={navClass}>Explore talent</NavLink>{user && <NavLink to="/dashboard" onClick={() => setOpen(false)} className={navClass}>Workspace</NavLink>}{user && <NavLink to="/chat" onClick={() => setOpen(false)} className={navClass}>Messages</NavLink>}{user?.role === 'admin' && <NavLink to="/admin" onClick={() => setOpen(false)} className={navClass}>Admin</NavLink>}</>;
  return <nav className="sticky top-0 z-40 border-b border-white/10 bg-primary/95 shadow-lg shadow-indigo-950/10 backdrop-blur"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="flex h-[72px] items-center justify-between"><Link to="/" className="flex items-center gap-2.5 text-white" onClick={() => setOpen(false)}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-teal-300 to-cyan-400 text-lg font-black text-primary shadow-lg shadow-cyan-900/30">S</span><span className="text-xl font-extrabold tracking-tight">SkillBridge</span></Link><button onClick={() => setOpen(!open)} className="rounded-lg p-2 text-white hover:bg-white/10 md:hidden" aria-label="Toggle navigation" aria-expanded={open}><span className="text-xl">{open ? '×' : '☰'}</span></button><div className="hidden items-center gap-1 md:flex"><Menu />{user ? <><span className="ml-2 hidden rounded-lg bg-white/10 px-3 py-2 text-sm text-white lg:block">Hi, {user.name?.split(' ')[0]}</span><button onClick={logout} className="ml-2 rounded-lg bg-white px-4 py-2 text-sm font-bold text-primary transition hover:bg-indigo-50">Log out</button></> : <><NavLink to="/login" className="ml-2 px-3 py-2 text-sm font-bold text-white">Log in</NavLink><NavLink to="/register" className="rounded-lg bg-teal-300 px-4 py-2 text-sm font-bold text-primary shadow-sm transition hover:bg-teal-200">Get started</NavLink></>}</div></div>{open && <div className="border-t border-white/15 pb-4 pt-2 md:hidden"><div className="flex flex-col gap-1"><Menu />{user ? <button onClick={logout} className="mt-2 rounded-lg bg-white px-4 py-2 text-left text-sm font-bold text-primary">Log out</button> : <div className="mt-2 grid grid-cols-2 gap-2"><NavLink onClick={() => setOpen(false)} to="/login" className="rounded-lg bg-white px-4 py-2 text-center text-sm font-bold text-primary">Log in</NavLink><NavLink onClick={() => setOpen(false)} to="/register" className="rounded-lg bg-teal-300 px-4 py-2 text-center text-sm font-bold text-primary">Get started</NavLink></div>}</div></div>}</div></nav>;
}
export default Navbar;
